# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nblockchain\"\xc2\x01\n\x0bTransaction\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x35\n\x04type\x18\x05 \x01(\x0e\x32\'.blockchain.Transaction.TransactionType\"7\n\x0fTransactionType\x12\x0c\n\x08TRANSFER\x10\x00\x12\t\n\x05STAKE\x10\x01\x12\x0b\n\x07UNSTAKE\x10\x02\"\x8c\x01\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\r\x12\x11\n\tprev_hash\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x11\n\tvalidator\x18\x04 \x01(\t\x12-\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x17.blockchain.Transaction\x12\x11\n\ttimestamp\x18\x06 \x01(\x01\"1\n\tBlockVote\x12\x10\n\x08voter_id\x18\x01 \x01(\t\x12\x12\n\nblock_hash\x18\x02 \x01(\t\"\x94\x03\n\x07Message\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.blockchain.Message.MessageType\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\t\x12%\n\x02tx\x18\x04 \x01(\x0b\x32\x17.blockchain.TransactionH\x00\x12\"\n\x05\x62lock\x18\x05 \x01(\x0b\x32\x11.blockchain.BlockH\x00\x12\x31\n\rsync_response\x18\x06 \x01(\x0b\x32\x18.blockchain.SyncResponseH\x00\x12+\n\nblock_vote\x18\x07 \x01(\x0b\x32\x15.blockchain.BlockVoteH\x00\"|\n\x0bMessageType\x12\t\n\x05HELLO\x10\x00\x12\x07\n\x03\x42YE\x10\x01\x12\x0f\n\x0bTRANSACTION\x10\x02\x12\t\n\x05\x42LOCK\x10\x03\x12\x10\n\x0cSYNC_REQUEST\x10\x04\x12\x11\n\rSYNC_RESPONSE\x10\x05\x12\x08\n\x04STEP\x10\x06\x12\x0e\n\nBLOCK_VOTE\x10\x07\x42\t\n\x07payload\"1\n\x0cSyncResponse\x12!\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x11.blockchain.Blockb\x06proto3')



_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_BLOCKVOTE = DESCRIPTOR.message_types_by_name['BlockVote']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_SYNCRESPONSE = DESCRIPTOR.message_types_by_name['SyncResponse']
_TRANSACTION_TRANSACTIONTYPE = _TRANSACTION.enum_types_by_name['TransactionType']
_MESSAGE_MESSAGETYPE = _MESSAGE.enum_types_by_name['MessageType']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Block)
  })
_sym_db.RegisterMessage(Block)

BlockVote = _reflection.GeneratedProtocolMessageType('BlockVote', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKVOTE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.BlockVote)
  })
_sym_db.RegisterMessage(BlockVote)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Message)
  })
_sym_db.RegisterMessage(Message)

SyncResponse = _reflection.GeneratedProtocolMessageType('SyncResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCRESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.SyncResponse)
  })
_sym_db.RegisterMessage(SyncResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTION._serialized_start=30
  _TRANSACTION._serialized_end=224
  _TRANSACTION_TRANSACTIONTYPE._serialized_start=169
  _TRANSACTION_TRANSACTIONTYPE._serialized_end=224
  _BLOCK._serialized_start=227
  _BLOCK._serialized_end=367
  _BLOCKVOTE._serialized_start=369
  _BLOCKVOTE._serialized_end=418
  _MESSAGE._serialized_start=421
  _MESSAGE._serialized_end=825
  _MESSAGE_MESSAGETYPE._serialized_start=690
  _MESSAGE_MESSAGETYPE._serialized_end=814
  _SYNCRESPONSE._serialized_start=827
  _SYNCRESPONSE._serialized_end=876
# @@protoc_insertion_point(module_scope)
